name: ECR
description: Login to ECR in your build steps
author: https://github.com/lox
requirements:
  - curl
  - bash
  - aws
configuration:
  properties:
    login:
      type: boolean
    account-ids:
      type:
        - string
        - array
      minItems: 1
    no-include-email:
      type: boolean
    region:
      type: string
    access-key-id:
      type: string
    secret-access-key-env:
      type: string
  required:
    - login
